#!/usr/bin/env node
'use strict'
const path = require('path')
const fs = require('fs')

const main = require('./main')

function cmdline(err, books) {
    if(err) {
        console.error(err)
        return
    }

    if(process.argv.length < 3) {
        show_random_chapter_1(books)
    } else {
        let args = process.argv.slice(2).join(' ')
        if(args == '-h' || args == '--help') showHelp()
        else if (args == '-b' || args == '--books') showBooks(books)
        else if (args == '-f' || args == '--fav') showFavs(books)
        else if (args == '--save') saveFav()
        else {
            omniSearch(books, args)
        }
    }

    function show_random_chapter_1(books) {
        let chap = main.randomChapter(books)
        consoleShow(chap)
        recordShown(chap)
    }

}

function showHelp() {
    console.log(`bible
Shows a chapter from the bible by default.
        -h|--help       : show this help
        -b|--books      : show list of bible books
        --save          : save last shown chapter as favorite
        -f|--fav        : show list of favorite chapters
        chapId          : show this chapter (eg: o19:23, psalms:23)
        the lord is my  : find matching verses
`)
}

function showBooks(books) {
    console.log('\tThe Old Testament')
    console.log('\t=================')
    for(let i = 0;i < books.length;i++) {
        if(books[i].testament == 'old') {
            console.log(`o${to_str_1(books[i])}`)
        }
    }

    console.log('')

    console.log('\tThe New Testament')
    console.log('\t=================')
    for(let i = 0;i < books.length;i++) {
        if(books[i].testament == 'new') {
            console.log(`n${to_str_1(books[i])}`)
        }
    }

    function to_str_1(book) {
        return `${book.num}\t${book.title.replace(/\n/g, ' ')}`
    }
}

/*      outcome/
 * See if the request is matches a chapter and return that.
 * If not return results as a phrase in the bible.
 */
function omniSearch(books, search) {
    let chap = main.loadChapter(books, search)
    if(chap) {
        consoleShow(chap)
        recordShown(chap)
    } else {
        let results = main.findResults(books, search)
        if(results && results.length) {
            consoleShowResults(results)
        } else {
            let bks = main.findMatchingBooks(books, search)
            if(bks && bks.length) consoleShowBooks(bks)
            else console.error(`(no results found)`)
        }
    }
}

const shown = path.join(__dirname, ".chapters-shown")
function recordShown(book) {
    if(book.chapter.num == 'xxx') return
    let id = main.chapterId(book)
    fs.appendFile(shown, `${id}\n`, (err) => {
        if(err) console.error(err)
        else console.log(id)
    })
}

const favs = path.join(__dirname, "favs")
function saveFav() {
    main.loadMetaFileLines(shown, (err, lines) => {
        if(err) console.error(err)
        else {
            let last = lines[lines.length-1]
            main.loadMetaFileLines(favs, (err, lines) => {
                if(err) console.error(err)
                else {
                    if(is_already_saved_1(last, lines)) {
                        already_saved_1(last)
                    } else {
                        append_to_favs_1(last)
                    }
                }
            })
        }
    })

    function is_already_saved_1(last, lines) {
        return lines.indexOf(last) != -1
    }

    function append_to_favs_1(last) {
        fs.appendFile(favs, `${last}\n`, (err) => {
            if(err) console.error(err)
            else console.log(`Saving ${last} as favorite`)
        })
    }

    function already_saved_1(last) {
        console.log(`${last} already saved as favorite`)
    }
}

function showFavs(books) {
    main.loadMetaFileLines(favs, (err, lines) => {
        if(err) console.error(err)
        else {
            for(let i = 0;i < lines.length;i++) {
                console.log(with_title_1(lines[i]))
            }
        }
    })

    function with_title_1(line) {
      let chap = main.loadChapter(books, line)
      if(chap) return `${line}\t${chap.title} (Chapter ${chap.chapter.num})`
      else return line
    }
}


function consoleShow(book) {
    let testament = 'the old testament'
    if(book.testament == 'new') testament = 'the new testament'
    console.log(`(from a book of ${testament} -`)

    console.log(`\t${book.title})`)
    console.log('===')
    console.log(book.chapter.txt.join('\n'))
}

function consoleShowResults(verses) {
    for(let i = 0;i < verses.length;i++) {
        let book = verses[i]
        console.log(book.result.join('\n'))
        console.log(main.chapterId(book))
    }
}

function consoleShowBooks(results) {
    console.log('Too many matching books found:')
    for(let i = 0;i < results.length;i++) {
        console.log(`\t${results[i].book.title}`)
    }
}

main.serve(cmdline)
